# Generated by Django 3.2 on 2021-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VistaCex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cita', models.IntegerField()),
                ('fecha', models.DateField(default='2021-01-01')),
                ('hora', models.CharField(default='', max_length=8)),
                ('consultorio', models.IntegerField()),
                ('especialidad', models.CharField(max_length=70)),
                ('medico', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=75)),
                ('estado_cita', models.CharField(max_length=10)),
                ('llamada', models.IntegerField()),
                ('atendido', models.IntegerField()),
            ],
        ),
    ]
