# Generated by Django 3.2 on 2021-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosHc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('contrato', models.CharField(max_length=30)),
            ],
        ),
    ]
