# Generated by Django 3.2 on 2021-09-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte02', '0002_contratoshc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsusariosContratosHc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('mpmeni', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarioshc',
            name='contrato',
        ),
    ]
