# Generated by Django 3.2 on 2021-05-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consul',
            name='consdet',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='consul',
            name='conscod',
            field=models.IntegerField(),
        ),
    ]
